version: '3.2'

services:
    baseapp:
        container_name: baseapp
        build: .
        volumes:
            - ./src:/vol/app
            # For dev server hot reloading
            - ./src:/vol/static/src
        ports:
            - 12000:3000
        working_dir: /vol/static
        environment:
            - REACT_APP_TITLE=Multi-tenancy Admin
            - APP_NAME=baseapp
            - GENEITY_ENV
